[package]
name = "universal-scanner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
socket2 = { workspace = true }
if-addrs = { workspace = true }
ipnet = { workspace = true }
pcap = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
ureq = { version = "2", default-features = false, features = ["tls"] }

[dev-dependencies]
tempfile = "3"
